/* eslint-disable camelcase, max-len */
'use strict';

exports.seed = (knex) => {
  return knex(`postures`).del().then(() => {
    return knex(`postures`)
    .insert([
      { name: `Urdhva Vriksasana` },
      { name: `Uttanasana A` },
      { name: `Uttanasana B` },
      { name: `Chaturanga Dandasana` },
      { name: `Urdhva-Mukha-Shvanasana` },
      { name: `Adho-Mukha-Shvanasana` },
      { name: `Samasthitih` },
      { name: `Utkatasana` },
      { name: `Virabhadrasana A` },
      { name: `Padangushthasana` },
      { name: `Pada-Hastasana` },
      { name: `Utthita Trikonasanaa` },
      { name: `Parivritta Trikonasana` },
      { name: `Utthita Parshvakonasana` },
      { name: `Prasarita Padottanasana A` },
      { name: `Prasarita Padottanasana B` },
      { name: `Prasarita Padottanasana C` },
      { name: `Prasarita Padottanasana D` },
      { name: `Parshvottanasana` },
      { name: `Utthita Hasta Padangushthasana` },
      { name: `Utthita Hasta Padangushthasana B` },
      { name: `Ardha Baddha Padmottanasana` },
      { name: `Virabhadrasana B` },
      { name: `Dandasana` },
      { name: `Paschimottanasana A` },
      { name: `Paschimottanasana B` },
      { name: `Paschimottanasana C` },
      { name: `Paschimottanasana D` },
      { name: `Purvottanasana` },
      { name: `Ardha Baddha Padma Paschimottanasana` },
      { name: `Tiryam-Mukha Eka-Pada Paschimottanasan` },
      { name: `Janu Shirshasana A` },
      { name: `Janu Shirshasana B` },
      { name: `Janu Shirshasana C` },
      { name: `Marichyasana A` },
      { name: `Marichyasana B` },
      { name: `Marichyasana C` },
      { name: `Marichyasana D` },
      { name: `Navasana` },
      { name: `Bhuja-Pidasana` },
      { name: `Kurmasana` },
      { name: `Supta-Kurmasana` },
      { name: `Garbha Pindasana` },
      { name: `Kukkutasana` },
      { name: `Baddha Konasana A` },
      { name: `Baddha Konasana B` },
      { name: `Baddha Konasana C` },
      { name: `Upavishtha Konasana A` },
      { name: `Upavishtha Konasana B` },
      { name: `Supta Konasana` },
      { name: `Supta Padangushthasana` },
      { name: `Supta Parshvasahita` },
      { name: `Ubhaya Padangushthasana` },
      { name: `Urdhva-Mukha Paschimottanasana` },
      { name: `Setu Bandhasana` },
      { name: `Urdhva Dhanurasana` },
      { name: `Chakrasana` },
      { name: `Pashasana` },
      { name: `Krounchasana` },
      { name: `Shalabhasana A` },
      { name: `Shalabhasana B` },
      { name: `Bhekasana` },
      { name: `Dhanurasana` },
      { name: `Parshva Dhanurasana` },
      { name: `Ushtrasana` },
      { name: `Laghu-Vajrasana` },
      { name: `Kapotasana A` },
      { name: `Kapotasana B` },
      { name: `Supta Vajrasana` },
      { name: `Bakasana A` },
      { name: `Bakasana B` },
      { name: `Bharadvajasana` },
      { name: `Ardha Matsyendrasana` },
      { name: `Eka-Pada Shirshasana` },
      { name: `Dvi-Pada Shirshasana` },
      { name: `Yoga-Nidrasana` },
      { name: `Tittibhasana A` },
      { name: `Tittibhasana B` },
      { name: `Tittibhasana C` },
      { name: `Pincha Mayurasana` },
      { name: `Karandavasana` },
      { name: `Mayurasana` },
      { name: `Nakrasana` },
      { name: `Vatayanasana` },
      { name: `Parighasana` },
      { name: `Gomukhasana A` },
      { name: `Gomukhasana B` },
      { name: `Supta Urdhva Pada Vajrasana` },
      { name: `Mukta Hasta Shirshasana A` },
      { name: `Mukta Hasta Shirshasana B` },
      { name: `Mukta Hasta Shirshasana C` },
      { name: `Baddha Hasta Shirshasana A` },
      { name: `Baddha Hasta Shirshasana B` },
      { name: `Baddha Hasta Shirshasana C` },
      { name: `Baddha Hasta Shirshasana D` },
      { name: `Paschimottanasana` },
      { name: `Vasishthasana` },
      { name: `Vishvamitrasana` },
      { name: `Kasyapasana` },
      { name: `Chakorasana` },
      { name: `Bhairavasana` },
      { name: `Skandasana` },
      { name: `Durvasana` },
      { name: `Urdhva Kukkutasana A` },
      { name: `Urdhva Kukkutasana B` },
      { name: `Urdhva Kukkutasana C` },
      { name: `Galavasana` },
      { name: `Eka-Pada Bakasana A` },
      { name: `Eka-Pada Bakasana B` },
      { name: `Purna Matsyendrasana` },
      { name: `Viranchyasana A` },
      { name: `Viranchyasana B` },
      { name: `Dvi-Pada Viparita Dandasana` },
      { name: `Eka-Pada Viparita Dandasana` },
      { name: `Viparita Shalabhasana` },
      { name: `Ganda Bherundasana` },
      { name: `Hanumanasana` },
      { name: `Supta Trivikramasana` },
      { name: `Digasana A` },
      { name: `Digasana B` },
      { name: `Utthita Trivikrimasana` },
      { name: `Nata Rajasana A` },
      { name: `Nata Rajasana B` },
      { name: `Raja Kapotasana` },
      { name: `Eka-Pada Raja Kapotasana` },
      { name: `Salamba Sarvangasana` },
      { name: `Halasana` },
      { name: `Karna-Pidasana` },
      { name: `Urdhva-Padmasana` },
      { name: `Pindasana` },
      { name: `Matsyasana` },
      { name: `Uttana Padasana` },
      { name: `Shirshasana A` },
      { name: `Shirshasana B` },
      { name: `Urdhva Dandasana` },
      { name: `Balasana` },
      { name: `Baddha Padmasana` },
      { name: `Yoga-Mudra` },
      { name: `Padmasana` },
      { name: `Utplutih` },
      { name: `Shavasana` },
    ]);
  });
};
